export default {
  ADD_POKEMON: "ADD_POKEMON",
  REMOVE_POKEMON: "REMOVE_POKEMON",
  GET_POKEMONS_REQUEST: "GET_POKEMONS_REQUEST",
  GET_POKEMONS_SUCCESS: "GET_POKEMONS_SUCCESS",
  GET_POKEMONS_FAILURE: "GET_POKEMONS_FAILURE",
};
